spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restApi?useTimezone=true&serverTimezone=UTC
    username: root
    password: 5037

  jpa:
    open-in-view: false 
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false